<?php

use Illuminate\Database\Seeder;

class CiudadTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('ciudad')->delete();

        $ciudades =
        [
            ['nombre' => 'Leticia', 'id_departamento' => 1],
            ['nombre' => 'Puerto Nariño', 'id_departamento' => 1],
            ['nombre' => 'Abejorral', 'id_departamento' => 2],
            ['nombre' => 'Abriaquí', 'id_departamento' => 2],
            ['nombre' => 'Alejandria', 'id_departamento' => 2],
            ['nombre' => 'Amagá', 'id_departamento' => 2],
            ['nombre' => 'Amalfi', 'id_departamento' => 2],
            ['nombre' => 'Andes', 'id_departamento' => 2],
            ['nombre' => 'Angelópolis', 'id_departamento' => 2],
            ['nombre' => 'Angostura', 'id_departamento' => 2],
            ['nombre' => 'Anorí', 'id_departamento' => 2],
            ['nombre' => 'Anzá', 'id_departamento' => 2],
            ['nombre' => 'Apartadó', 'id_departamento' => 2],
            ['nombre' => 'Arboletes', 'id_departamento' => 2],
            ['nombre' => 'Argelia', 'id_departamento' => 2],
            ['nombre' => 'Armenia', 'id_departamento' => 2],
            ['nombre' => 'Barbosa', 'id_departamento' => 2],
            ['nombre' => 'Bello', 'id_departamento' => 2],
            ['nombre' => 'Belmira', 'id_departamento' => 2],
            ['nombre' => 'Betania', 'id_departamento' => 2],
            ['nombre' => 'Betulia', 'id_departamento' => 2],
            ['nombre' => 'Bolívar', 'id_departamento' => 2],
            ['nombre' => 'Briceño', 'id_departamento' => 2],
            ['nombre' => 'Burítica', 'id_departamento' => 2],
            ['nombre' => 'Caicedo', 'id_departamento' => 2],
            ['nombre' => 'Caldas', 'id_departamento' => 2],
            ['nombre' => 'Campamento', 'id_departamento' => 2],
            ['nombre' => 'Caracolí', 'id_departamento' => 2],
            ['nombre' => 'Caramanta', 'id_departamento' => 2],
            ['nombre' => 'Carepa', 'id_departamento' => 2],
            ['nombre' => 'Carmen de Viboral', 'id_departamento' => 2],
            ['nombre' => 'Carolina', 'id_departamento' => 2],
            ['nombre' => 'Caucasia', 'id_departamento' => 2],
            ['nombre' => 'Cañasgordas', 'id_departamento' => 2],
            ['nombre' => 'Chigorodó', 'id_departamento' => 2],
            ['nombre' => 'Cisneros', 'id_departamento' => 2],
            ['nombre' => 'Cocorná', 'id_departamento' => 2],
            ['nombre' => 'Concepción', 'id_departamento' => 2],
            ['nombre' => 'Concordia', 'id_departamento' => 2],
            ['nombre' => 'Copacabana', 'id_departamento' => 2],
            ['nombre' => 'Cáceres', 'id_departamento' => 2],
            ['nombre' => 'Dabeiba', 'id_departamento' => 2],
            ['nombre' => 'Don Matías', 'id_departamento' => 2],
            ['nombre' => 'Ebéjico', 'id_departamento' => 2],
            ['nombre' => 'El Bagre', 'id_departamento' => 2],
            ['nombre' => 'Entrerríos', 'id_departamento' => 2],
            ['nombre' => 'Envigado', 'id_departamento' => 2],
            ['nombre' => 'Fredonia', 'id_departamento' => 2],
            ['nombre' => 'Frontino', 'id_departamento' => 2],
            ['nombre' => 'Giraldo', 'id_departamento' => 2],
            ['nombre' => 'Girardota', 'id_departamento' => 2],
            ['nombre' => 'Granada', 'id_departamento' => 2],
            ['nombre' => 'Guadalupe', 'id_departamento' => 2],
            ['nombre' => 'Guarne', 'id_departamento' => 2],
            ['nombre' => 'Guatapé', 'id_departamento' => 2],
            ['nombre' => 'Gómez Plata', 'id_departamento' => 2],
            ['nombre' => 'Heliconia', 'id_departamento' => 2],
            ['nombre' => 'Hispania', 'id_departamento' => 2],
            ['nombre' => 'Itagüí', 'id_departamento' => 2],
            ['nombre' => 'Ituango', 'id_departamento' => 2],
            ['nombre' => 'Jardín', 'id_departamento' => 2],
            ['nombre' => 'Jericó', 'id_departamento' => 2],
            ['nombre' => 'La Ceja', 'id_departamento' => 2],
            ['nombre' => 'La Estrella', 'id_departamento' => 2],
            ['nombre' => 'La Pintada', 'id_departamento' => 2],
            ['nombre' => 'La Unión', 'id_departamento' => 2],
            ['nombre' => 'Liborina', 'id_departamento' => 2],
            ['nombre' => 'Maceo', 'id_departamento' => 2],
            ['nombre' => 'Marinilla', 'id_departamento' => 2],
            ['nombre' => 'Medellín', 'id_departamento' => 2],
            ['nombre' => 'Montebello', 'id_departamento' => 2],
            ['nombre' => 'Murindó', 'id_departamento' => 2],
            ['nombre' => 'Mutatá', 'id_departamento' => 2],
            ['nombre' => 'Nariño', 'id_departamento' => 2],
            ['nombre' => 'Nechí', 'id_departamento' => 2],
            ['nombre' => 'Necoclí', 'id_departamento' => 2],
            ['nombre' => 'Olaya', 'id_departamento' => 2],
            ['nombre' => 'Peque', 'id_departamento' => 2],
            ['nombre' => 'Peñol', 'id_departamento' => 2],
            ['nombre' => 'Pueblorrico', 'id_departamento' => 2],
            ['nombre' => 'Puerto Berrío', 'id_departamento' => 2],
            ['nombre' => 'Puerto Nare', 'id_departamento' => 2],
            ['nombre' => 'Puerto Triunfo', 'id_departamento' => 2],
            ['nombre' => 'Remedios', 'id_departamento' => 2],
            ['nombre' => 'Retiro', 'id_departamento' => 2],
            ['nombre' => 'Ríonegro', 'id_departamento' => 2],
            ['nombre' => 'Sabanalarga', 'id_departamento' => 2],
            ['nombre' => 'Sabaneta', 'id_departamento' => 2],
            ['nombre' => 'Salgar', 'id_departamento' => 2],
            ['nombre' => 'San Andrés de Cuerquía', 'id_departamento' => 2],
            ['nombre' => 'San Carlos', 'id_departamento' => 2],
            ['nombre' => 'San Francisco', 'id_departamento' => 2],
            ['nombre' => 'San Jerónimo', 'id_departamento' => 2],
            ['nombre' => 'San José de Montaña', 'id_departamento' => 2],
            ['nombre' => 'San Juan de Urabá', 'id_departamento' => 2],
            ['nombre' => 'San Luís', 'id_departamento' => 2],
            ['nombre' => 'San Pedro', 'id_departamento' => 2],
            ['nombre' => 'San Pedro de Urabá', 'id_departamento' => 2],
            ['nombre' => 'San Rafael', 'id_departamento' => 2],
            ['nombre' => 'San Roque', 'id_departamento' => 2],
            ['nombre' => 'San Vicente', 'id_departamento' => 2],
            ['nombre' => 'Santa Bárbara', 'id_departamento' => 2],
            ['nombre' => 'Santa Fé de Antioquia', 'id_departamento' => 2],
            ['nombre' => 'Santa Rosa de Osos', 'id_departamento' => 2],
            ['nombre' => 'Santo Domingo', 'id_departamento' => 2],
            ['nombre' => 'Santuario', 'id_departamento' => 2],
            ['nombre' => 'Segovia', 'id_departamento' => 2],
            ['nombre' => 'Sonsón', 'id_departamento' => 2],
            ['nombre' => 'Sopetrán', 'id_departamento' => 2],
            ['nombre' => 'Tarazá', 'id_departamento' => 2],
            ['nombre' => 'Tarso', 'id_departamento' => 2],
            ['nombre' => 'Titiribí', 'id_departamento' => 2],
            ['nombre' => 'Toledo', 'id_departamento' => 2],
            ['nombre' => 'Turbo', 'id_departamento' => 2],
            ['nombre' => 'Támesis', 'id_departamento' => 2],
            ['nombre' => 'Uramita', 'id_departamento' => 2],
            ['nombre' => 'Urrao', 'id_departamento' => 2],
            ['nombre' => 'Valdivia', 'id_departamento' => 2],
            ['nombre' => 'Valparaiso', 'id_departamento' => 2],
            ['nombre' => 'Vegachí', 'id_departamento' => 2],
            ['nombre' => 'Venecia', 'id_departamento' => 2],
            ['nombre' => 'Vigía del Fuerte', 'id_departamento' => 2],
            ['nombre' => 'Yalí', 'id_departamento' => 2],
            ['nombre' => 'Yarumal', 'id_departamento' => 2],
            ['nombre' => 'Yolombó', 'id_departamento' => 2],
            ['nombre' => 'Yondó (Casabe)', 'id_departamento' => 2],
            ['nombre' => 'Zaragoza', 'id_departamento' => 2],
            ['nombre' => 'Arauca', 'id_departamento' => 4],
            ['nombre' => 'Arauquita', 'id_departamento' => 4],
            ['nombre' => 'Cravo Norte', 'id_departamento' => 4],
            ['nombre' => 'Fortúl', 'id_departamento' => 4],
            ['nombre' => 'Puerto Rondón', 'id_departamento' => 4],
            ['nombre' => 'Saravena', 'id_departamento' => 4],
            ['nombre' => 'Tame', 'id_departamento' => 4],
            ['nombre' => 'Baranoa', 'id_departamento' => 5],
            ['nombre' => 'Barranquilla', 'id_departamento' => 5],
            ['nombre' => 'Campo de la Cruz', 'id_departamento' => 5],
            ['nombre' => 'Candelaria', 'id_departamento' => 5],
            ['nombre' => 'Galapa', 'id_departamento' => 5],
            ['nombre' => 'Juan de Acosta', 'id_departamento' => 5],
            ['nombre' => 'Luruaco', 'id_departamento' => 5],
            ['nombre' => 'Malambo', 'id_departamento' => 5],
            ['nombre' => 'Manatí', 'id_departamento' => 5],
            ['nombre' => 'Palmar de Varela', 'id_departamento' => 5],
            ['nombre' => 'Piojo', 'id_departamento' => 5],
            ['nombre' => 'Polonuevo', 'id_departamento' => 5],
            ['nombre' => 'Ponedera', 'id_departamento' => 5],
            ['nombre' => 'Puerto Colombia', 'id_departamento' => 5],
            ['nombre' => 'Repelón', 'id_departamento' => 5],
            ['nombre' => 'Sabanagrande', 'id_departamento' => 5],
            ['nombre' => 'Sabanalarga', 'id_departamento' => 5],
            ['nombre' => 'Santa Lucía', 'id_departamento' => 5],
            ['nombre' => 'Santo Tomás', 'id_departamento' => 5],
            ['nombre' => 'Soledad', 'id_departamento' => 5],
            ['nombre' => 'Suan', 'id_departamento' => 5],
            ['nombre' => 'Tubará', 'id_departamento' => 5],
            ['nombre' => 'Usiacuri', 'id_departamento' => 5],
            ['nombre' => 'Achí', 'id_departamento' => 6],
            ['nombre' => 'Altos del Rosario', 'id_departamento' => 6],
            ['nombre' => 'Arenal', 'id_departamento' => 6],
            ['nombre' => 'Arjona', 'id_departamento' => 6],
            ['nombre' => 'Arroyohondo', 'id_departamento' => 6],
            ['nombre' => 'Barranco de Loba', 'id_departamento' => 6],
            ['nombre' => 'Calamar', 'id_departamento' => 6],
            ['nombre' => 'Cantagallo', 'id_departamento' => 6],
            ['nombre' => 'Cartagena', 'id_departamento' => 6],
            ['nombre' => 'Cicuco', 'id_departamento' => 6],
            ['nombre' => 'Clemencia', 'id_departamento' => 6],
            ['nombre' => 'Córdoba', 'id_departamento' => 6],
            ['nombre' => 'El Carmen de Bolívar', 'id_departamento' => 6],
            ['nombre' => 'El Guamo', 'id_departamento' => 6],
            ['nombre' => 'El Peñon', 'id_departamento' => 6],
            ['nombre' => 'Hatillo de Loba', 'id_departamento' => 6],
            ['nombre' => 'Magangué', 'id_departamento' => 6],
            ['nombre' => 'Mahates', 'id_departamento' => 6],
            ['nombre' => 'Margarita', 'id_departamento' => 6],
            ['nombre' => 'María la Baja', 'id_departamento' => 6],
            ['nombre' => 'Mompós', 'id_departamento' => 6],
            ['nombre' => 'Montecristo', 'id_departamento' => 6],
            ['nombre' => 'Morales', 'id_departamento' => 6],
            ['nombre' => 'Norosí', 'id_departamento' => 6],
            ['nombre' => 'Pinillos', 'id_departamento' => 6],
            ['nombre' => 'Regidor', 'id_departamento' => 6],
            ['nombre' => 'Río Viejo', 'id_departamento' => 6],
            ['nombre' => 'San Cristobal', 'id_departamento' => 6],
            ['nombre' => 'San Estanislao', 'id_departamento' => 6],
            ['nombre' => 'San Fernando', 'id_departamento' => 6],
            ['nombre' => 'San Jacinto', 'id_departamento' => 6],
            ['nombre' => 'San Jacinto del Cauca', 'id_departamento' => 6],
            ['nombre' => 'San Juan de Nepomuceno', 'id_departamento' => 6],
            ['nombre' => 'San Martín de Loba', 'id_departamento' => 6],
            ['nombre' => 'San Pablo', 'id_departamento' => 6],
            ['nombre' => 'Santa Catalina', 'id_departamento' => 6],
            ['nombre' => 'Santa Rosa ', 'id_departamento' => 6],
            ['nombre' => 'Santa Rosa del Sur', 'id_departamento' => 6],
            ['nombre' => 'Simití', 'id_departamento' => 6],
            ['nombre' => 'Soplaviento', 'id_departamento' => 6],
            ['nombre' => 'Talaigua Nuevo', 'id_departamento' => 6],
            ['nombre' => 'Tiquisio (Puerto Rico)', 'id_departamento' => 6],
            ['nombre' => 'Turbaco', 'id_departamento' => 6],
            ['nombre' => 'Turbaná', 'id_departamento' => 6],
            ['nombre' => 'Villanueva', 'id_departamento' => 6],
            ['nombre' => 'Zambrano', 'id_departamento' => 6],
            ['nombre' => 'Almeida', 'id_departamento' => 7],
            ['nombre' => 'Aquitania', 'id_departamento' => 7],
            ['nombre' => 'Arcabuco', 'id_departamento' => 7],
            ['nombre' => 'Belén', 'id_departamento' => 7],
            ['nombre' => 'Berbeo', 'id_departamento' => 7],
            ['nombre' => 'Beteitiva', 'id_departamento' => 7],
            ['nombre' => 'Boavita', 'id_departamento' => 7],
            ['nombre' => 'Boyacá', 'id_departamento' => 7],
            ['nombre' => 'Briceño', 'id_departamento' => 7],
            ['nombre' => 'Buenavista', 'id_departamento' => 7],
            ['nombre' => 'Busbanza', 'id_departamento' => 7],
            ['nombre' => 'Caldas', 'id_departamento' => 7],
            ['nombre' => 'Campohermoso', 'id_departamento' => 7],
            ['nombre' => 'Cerinza', 'id_departamento' => 7],
            ['nombre' => 'Chinavita', 'id_departamento' => 7],
            ['nombre' => 'Chiquinquirá', 'id_departamento' => 7],
            ['nombre' => 'Chiscas', 'id_departamento' => 7],
            ['nombre' => 'Chita', 'id_departamento' => 7],
            ['nombre' => 'Chitaraque', 'id_departamento' => 7],
            ['nombre' => 'Chivatá', 'id_departamento' => 7],
            ['nombre' => 'Chíquiza', 'id_departamento' => 7],
            ['nombre' => 'Chívor', 'id_departamento' => 7],
            ['nombre' => 'Ciénaga', 'id_departamento' => 7],
            ['nombre' => 'Coper', 'id_departamento' => 7],
            ['nombre' => 'Corrales', 'id_departamento' => 7],
            ['nombre' => 'Covarachía', 'id_departamento' => 7],
            ['nombre' => 'Cubará', 'id_departamento' => 7],
            ['nombre' => 'Cucaita', 'id_departamento' => 7],
            ['nombre' => 'Cuitiva', 'id_departamento' => 7],
            ['nombre' => 'Cómbita', 'id_departamento' => 7],
            ['nombre' => 'Duitama', 'id_departamento' => 7],
            ['nombre' => 'El Cocuy', 'id_departamento' => 7],
            ['nombre' => 'El Espino', 'id_departamento' => 7],
            ['nombre' => 'Firavitoba', 'id_departamento' => 7],
            ['nombre' => 'Floresta', 'id_departamento' => 7],
            ['nombre' => 'Gachantivá', 'id_departamento' => 7],
            ['nombre' => 'Garagoa', 'id_departamento' => 7],
            ['nombre' => 'Guacamayas', 'id_departamento' => 7],
            ['nombre' => 'Guateque', 'id_departamento' => 7],
            ['nombre' => 'Guayatá', 'id_departamento' => 7],
            ['nombre' => 'Guicán', 'id_departamento' => 7],
            ['nombre' => 'Gámeza', 'id_departamento' => 7],
            ['nombre' => 'Izá', 'id_departamento' => 7],
            ['nombre' => 'Jenesano', 'id_departamento' => 7],
            ['nombre' => 'Jericó', 'id_departamento' => 7],
            ['nombre' => 'La Capilla', 'id_departamento' => 7],
            ['nombre' => 'La Uvita', 'id_departamento' => 7],
            ['nombre' => 'La Victoria', 'id_departamento' => 7],
            ['nombre' => 'Labranzagrande', 'id_departamento' => 7],
            ['nombre' => 'Macanal', 'id_departamento' => 7],
            ['nombre' => 'Maripí', 'id_departamento' => 7],
            ['nombre' => 'Miraflores', 'id_departamento' => 7],
            ['nombre' => 'Mongua', 'id_departamento' => 7],
            ['nombre' => 'Monguí', 'id_departamento' => 7],
            ['nombre' => 'Moniquirá', 'id_departamento' => 7],
            ['nombre' => 'Motavita', 'id_departamento' => 7],
            ['nombre' => 'Muzo', 'id_departamento' => 7],
            ['nombre' => 'Nobsa', 'id_departamento' => 7],
            ['nombre' => 'Nuevo Colón', 'id_departamento' => 7],
            ['nombre' => 'Oicatá', 'id_departamento' => 7],
            ['nombre' => 'Otanche', 'id_departamento' => 7],
            ['nombre' => 'Pachavita', 'id_departamento' => 7],
            ['nombre' => 'Paipa', 'id_departamento' => 7],
            ['nombre' => 'Pajarito', 'id_departamento' => 7],
            ['nombre' => 'Panqueba', 'id_departamento' => 7],
            ['nombre' => 'Pauna', 'id_departamento' => 7],
            ['nombre' => 'Paya', 'id_departamento' => 7],
            ['nombre' => 'Paz de Río', 'id_departamento' => 7],
            ['nombre' => 'Pesca', 'id_departamento' => 7],
            ['nombre' => 'Pisva', 'id_departamento' => 7],
            ['nombre' => 'Puerto Boyacá', 'id_departamento' => 7],
            ['nombre' => 'Páez', 'id_departamento' => 7],
            ['nombre' => 'Quipama', 'id_departamento' => 7],
            ['nombre' => 'Ramiriquí', 'id_departamento' => 7],
            ['nombre' => 'Rondón', 'id_departamento' => 7],
            ['nombre' => 'Ráquira', 'id_departamento' => 7],
            ['nombre' => 'Saboyá', 'id_departamento' => 7],
            ['nombre' => 'Samacá', 'id_departamento' => 7],
            ['nombre' => 'San Eduardo', 'id_departamento' => 7],
            ['nombre' => 'San José de Pare', 'id_departamento' => 7],
            ['nombre' => 'San Luís de Gaceno', 'id_departamento' => 7],
            ['nombre' => 'San Mateo', 'id_departamento' => 7],
            ['nombre' => 'San Miguel de Sema', 'id_departamento' => 7],
            ['nombre' => 'San Pablo de Borbur', 'id_departamento' => 7],
            ['nombre' => 'Santa María', 'id_departamento' => 7],
            ['nombre' => 'Santa Rosa de Viterbo', 'id_departamento' => 7],
            ['nombre' => 'Santa Sofía', 'id_departamento' => 7],
            ['nombre' => 'Santana', 'id_departamento' => 7],
            ['nombre' => 'Sativanorte', 'id_departamento' => 7],
            ['nombre' => 'Sativasur', 'id_departamento' => 7],
            ['nombre' => 'Siachoque', 'id_departamento' => 7],
            ['nombre' => 'Soatá', 'id_departamento' => 7],
            ['nombre' => 'Socha', 'id_departamento' => 7],
            ['nombre' => 'Socotá', 'id_departamento' => 7],
            ['nombre' => 'Sogamoso', 'id_departamento' => 7],
            ['nombre' => 'Somondoco', 'id_departamento' => 7],
            ['nombre' => 'Sora', 'id_departamento' => 7],
            ['nombre' => 'Soracá', 'id_departamento' => 7],
            ['nombre' => 'Sotaquirá', 'id_departamento' => 7],
            ['nombre' => 'Susacón', 'id_departamento' => 7],
            ['nombre' => 'Sutamarchán', 'id_departamento' => 7],
            ['nombre' => 'Sutatenza', 'id_departamento' => 7],
            ['nombre' => 'Sáchica', 'id_departamento' => 7],
            ['nombre' => 'Tasco', 'id_departamento' => 7],
            ['nombre' => 'Tenza', 'id_departamento' => 7],
            ['nombre' => 'Tibaná', 'id_departamento' => 7],
            ['nombre' => 'Tibasosa', 'id_departamento' => 7],
            ['nombre' => 'Tinjacá', 'id_departamento' => 7],
            ['nombre' => 'Tipacoque', 'id_departamento' => 7],
            ['nombre' => 'Toca', 'id_departamento' => 7],
            ['nombre' => 'Toguí', 'id_departamento' => 7],
            ['nombre' => 'Topagá', 'id_departamento' => 7],
            ['nombre' => 'Tota', 'id_departamento' => 7],
            ['nombre' => 'Tunja', 'id_departamento' => 7],
            ['nombre' => 'Tunungua', 'id_departamento' => 7],
            ['nombre' => 'Turmequé', 'id_departamento' => 7],
            ['nombre' => 'Tuta', 'id_departamento' => 7],
            ['nombre' => 'Tutasá', 'id_departamento' => 7],
            ['nombre' => 'Ventaquemada', 'id_departamento' => 7],
            ['nombre' => 'Villa de Leiva', 'id_departamento' => 7],
            ['nombre' => 'Viracachá', 'id_departamento' => 7],
            ['nombre' => 'Zetaquirá', 'id_departamento' => 7],
            ['nombre' => 'Úmbita', 'id_departamento' => 7],
            ['nombre' => 'Aguadas', 'id_departamento' => 8],
            ['nombre' => 'Anserma', 'id_departamento' => 8],
            ['nombre' => 'Aranzazu', 'id_departamento' => 8],
            ['nombre' => 'Belalcázar', 'id_departamento' => 8],
            ['nombre' => 'Chinchiná', 'id_departamento' => 8],
            ['nombre' => 'Filadelfia', 'id_departamento' => 8],
            ['nombre' => 'La Dorada', 'id_departamento' => 8],
            ['nombre' => 'La Merced', 'id_departamento' => 8],
            ['nombre' => 'La Victoria', 'id_departamento' => 8],
            ['nombre' => 'Manizales', 'id_departamento' => 8],
            ['nombre' => 'Manzanares', 'id_departamento' => 8],
            ['nombre' => 'Marmato', 'id_departamento' => 8],
            ['nombre' => 'Marquetalia', 'id_departamento' => 8],
            ['nombre' => 'Marulanda', 'id_departamento' => 8],
            ['nombre' => 'Neira', 'id_departamento' => 8],
            ['nombre' => 'Norcasia', 'id_departamento' => 8],
            ['nombre' => 'Palestina', 'id_departamento' => 8],
            ['nombre' => 'Pensilvania', 'id_departamento' => 8],
            ['nombre' => 'Pácora', 'id_departamento' => 8],
            ['nombre' => 'Risaralda', 'id_departamento' => 8],
            ['nombre' => 'Río Sucio', 'id_departamento' => 8],
            ['nombre' => 'Salamina', 'id_departamento' => 8],
            ['nombre' => 'Samaná', 'id_departamento' => 8],
            ['nombre' => 'San José', 'id_departamento' => 8],
            ['nombre' => 'Supía', 'id_departamento' => 8],
            ['nombre' => 'Villamaría', 'id_departamento' => 8],
            ['nombre' => 'Viterbo', 'id_departamento' => 8],
            ['nombre' => 'Albania', 'id_departamento' => 12],
            ['nombre' => 'Belén de los Andaquíes', 'id_departamento' => 12],
            ['nombre' => 'Cartagena del Chairá', 'id_departamento' => 12],
            ['nombre' => 'Curillo', 'id_departamento' => 12],
            ['nombre' => 'El Doncello', 'id_departamento' => 12],
            ['nombre' => 'El Paujil', 'id_departamento' => 12],
            ['nombre' => 'Florencia', 'id_departamento' => 12],
            ['nombre' => 'La Montañita', 'id_departamento' => 12],
            ['nombre' => 'Milán', 'id_departamento' => 12],
            ['nombre' => 'Morelia', 'id_departamento' => 12],
            ['nombre' => 'Puerto Rico', 'id_departamento' => 12],
            ['nombre' => 'San José del Fragua', 'id_departamento' => 12],
            ['nombre' => 'San Vicente del Caguán', 'id_departamento' => 12],
            ['nombre' => 'Solano', 'id_departamento' => 12],
            ['nombre' => 'Solita', 'id_departamento' => 12],
            ['nombre' => 'Valparaiso', 'id_departamento' => 12],
            ['nombre' => 'Aguazul', 'id_departamento' => 14],
            ['nombre' => 'Chámeza', 'id_departamento' => 14],
            ['nombre' => 'Hato Corozal', 'id_departamento' => 14],
            ['nombre' => 'La Salina', 'id_departamento' => 14],
            ['nombre' => 'Maní', 'id_departamento' => 14],
            ['nombre' => 'Monterrey', 'id_departamento' => 14],
            ['nombre' => 'Nunchía', 'id_departamento' => 14],
            ['nombre' => 'Orocué', 'id_departamento' => 14],
            ['nombre' => 'Paz de Ariporo', 'id_departamento' => 14],
            ['nombre' => 'Pore', 'id_departamento' => 14],
            ['nombre' => 'Recetor', 'id_departamento' => 14],
            ['nombre' => 'Sabanalarga', 'id_departamento' => 14],
            ['nombre' => 'San Luís de Palenque', 'id_departamento' => 14],
            ['nombre' => 'Sácama', 'id_departamento' => 14],
            ['nombre' => 'Tauramena', 'id_departamento' => 14],
            ['nombre' => 'Trinidad', 'id_departamento' => 14],
            ['nombre' => 'Támara', 'id_departamento' => 14],
            ['nombre' => 'Villanueva', 'id_departamento' => 14],
            ['nombre' => 'Yopal', 'id_departamento' => 14],
            ['nombre' => 'Almaguer', 'id_departamento' => 15],
            ['nombre' => 'Argelia', 'id_departamento' => 15],
            ['nombre' => 'Balboa', 'id_departamento' => 15],
            ['nombre' => 'Bolívar', 'id_departamento' => 15],
            ['nombre' => 'Buenos Aires', 'id_departamento' => 15],
            ['nombre' => 'Cajibío', 'id_departamento' => 15],
            ['nombre' => 'Caldono', 'id_departamento' => 15],
            ['nombre' => 'Caloto', 'id_departamento' => 15],
            ['nombre' => 'Corinto', 'id_departamento' => 15],
            ['nombre' => 'El Tambo', 'id_departamento' => 15],
            ['nombre' => 'Florencia', 'id_departamento' => 15],
            ['nombre' => 'Guachené', 'id_departamento' => 15],
            ['nombre' => 'Guapí', 'id_departamento' => 15],
            ['nombre' => 'Inzá', 'id_departamento' => 15],
            ['nombre' => 'Jambaló', 'id_departamento' => 15],
            ['nombre' => 'La Sierra', 'id_departamento' => 15],
            ['nombre' => 'La Vega', 'id_departamento' => 15],
            ['nombre' => 'López (Micay)', 'id_departamento' => 15],
            ['nombre' => 'Mercaderes', 'id_departamento' => 15],
            ['nombre' => 'Miranda', 'id_departamento' => 15],
            ['nombre' => 'Morales', 'id_departamento' => 15],
            ['nombre' => 'Padilla', 'id_departamento' => 15],
            ['nombre' => 'Patía (El Bordo)', 'id_departamento' => 15],
            ['nombre' => 'Piamonte', 'id_departamento' => 15],
            ['nombre' => 'Piendamó', 'id_departamento' => 15],
            ['nombre' => 'Popayán', 'id_departamento' => 15],
            ['nombre' => 'Puerto Tejada', 'id_departamento' => 15],
            ['nombre' => 'Puracé (Coconuco)', 'id_departamento' => 15],
            ['nombre' => 'Páez (Belalcazar)', 'id_departamento' => 15],
            ['nombre' => 'Rosas', 'id_departamento' => 15],
            ['nombre' => 'San Sebastián', 'id_departamento' => 15],
            ['nombre' => 'Santa Rosa', 'id_departamento' => 15],
            ['nombre' => 'Santander de Quilichao', 'id_departamento' => 15],
            ['nombre' => 'Silvia', 'id_departamento' => 15],
            ['nombre' => 'Sotara (Paispamba)', 'id_departamento' => 15],
            ['nombre' => 'Sucre', 'id_departamento' => 15],
            ['nombre' => 'Suárez', 'id_departamento' => 15],
            ['nombre' => 'Timbiquí', 'id_departamento' => 15],
            ['nombre' => 'Timbío', 'id_departamento' => 15],
            ['nombre' => 'Toribío', 'id_departamento' => 15],
            ['nombre' => 'Totoró', 'id_departamento' => 15],
            ['nombre' => 'Villa Rica', 'id_departamento' => 15],
            ['nombre' => 'Aguachica', 'id_departamento' => 9],
            ['nombre' => 'Agustín Codazzi', 'id_departamento' => 9],
            ['nombre' => 'Astrea', 'id_departamento' => 9],
            ['nombre' => 'Becerríl', 'id_departamento' => 9],
            ['nombre' => 'Bosconia', 'id_departamento' => 9],
            ['nombre' => 'Chimichagua', 'id_departamento' => 9],
            ['nombre' => 'Chiriguaná', 'id_departamento' => 9],
            ['nombre' => 'Curumaní', 'id_departamento' => 9],
            ['nombre' => 'El Copey', 'id_departamento' => 9],
            ['nombre' => 'El Paso', 'id_departamento' => 9],
            ['nombre' => 'Gamarra', 'id_departamento' => 9],
            ['nombre' => 'Gonzalez', 'id_departamento' => 9],
            ['nombre' => 'La Gloria', 'id_departamento' => 9],
            ['nombre' => 'La Jagua de Ibirico', 'id_departamento' => 9],
            ['nombre' => 'La Paz (Robles)', 'id_departamento' => 9],
            ['nombre' => 'Manaure Balcón del Cesar', 'id_departamento' => 9],
            ['nombre' => 'Pailitas', 'id_departamento' => 9],
            ['nombre' => 'Pelaya', 'id_departamento' => 9],
            ['nombre' => 'Pueblo Bello', 'id_departamento' => 9],
            ['nombre' => 'Río de oro', 'id_departamento' => 9],
            ['nombre' => 'San Alberto', 'id_departamento' => 9],
            ['nombre' => 'San Diego', 'id_departamento' => 9],
            ['nombre' => 'San Martín', 'id_departamento' => 9],
            ['nombre' => 'Tamalameque', 'id_departamento' => 9],
            ['nombre' => 'Valledupar', 'id_departamento' => 9],
            ['nombre' => 'Acandí', 'id_departamento' => 11],
            ['nombre' => 'Alto Baudó (Pie de Pato)', 'id_departamento' => 11],
            ['nombre' => 'Atrato (Yuto)', 'id_departamento' => 11],
            ['nombre' => 'Bagadó', 'id_departamento' => 11],
            ['nombre' => 'Bahía Solano (Mútis)', 'id_departamento' => 11],
            ['nombre' => 'Bajo Baudó (Pizarro)', 'id_departamento' => 11],
            ['nombre' => 'Belén de Bajirá', 'id_departamento' => 11],
            ['nombre' => 'Bojayá (Bellavista)', 'id_departamento' => 11],
            ['nombre' => 'Cantón de San Pablo', 'id_departamento' => 11],
            ['nombre' => 'Carmen del Darién (CURBARADÓ)', 'id_departamento' => 11],
            ['nombre' => 'Condoto', 'id_departamento' => 11],
            ['nombre' => 'Cértegui', 'id_departamento' => 11],
            ['nombre' => 'El Carmen de Atrato', 'id_departamento' => 11],
            ['nombre' => 'Istmina', 'id_departamento' => 11],
            ['nombre' => 'Juradó', 'id_departamento' => 11],
            ['nombre' => 'Lloró', 'id_departamento' => 11],
            ['nombre' => 'Medio Atrato', 'id_departamento' => 11],
            ['nombre' => 'Medio Baudó', 'id_departamento' => 11],
            ['nombre' => 'Medio San Juan (ANDAGOYA)', 'id_departamento' => 11],
            ['nombre' => 'Novita', 'id_departamento' => 11],
            ['nombre' => 'Nuquí', 'id_departamento' => 11],
            ['nombre' => 'Quibdó', 'id_departamento' => 11],
            ['nombre' => 'Río Iró', 'id_departamento' => 11],
            ['nombre' => 'Río Quito', 'id_departamento' => 11],
            ['nombre' => 'Ríosucio', 'id_departamento' => 11],
            ['nombre' => 'San José del Palmar', 'id_departamento' => 11],
            ['nombre' => 'Santa Genoveva de Docorodó', 'id_departamento' => 11],
            ['nombre' => 'Sipí', 'id_departamento' => 11],
            ['nombre' => 'Tadó', 'id_departamento' => 11],
            ['nombre' => 'Unguía', 'id_departamento' => 11],
            ['nombre' => 'Unión Panamericana (ÁNIMAS)', 'id_departamento' => 11],
            ['nombre' => 'Ayapel', 'id_departamento' => 13],
            ['nombre' => 'Buenavista', 'id_departamento' => 13],
            ['nombre' => 'Canalete', 'id_departamento' => 13],
            ['nombre' => 'Cereté', 'id_departamento' => 13],
            ['nombre' => 'Chimá', 'id_departamento' => 13],
            ['nombre' => 'Chinú', 'id_departamento' => 13],
            ['nombre' => 'Ciénaga de Oro', 'id_departamento' => 13],
            ['nombre' => 'Cotorra', 'id_departamento' => 13],
            ['nombre' => 'La Apartada y La Frontera', 'id_departamento' => 13],
            ['nombre' => 'Lorica', 'id_departamento' => 13],
            ['nombre' => 'Los Córdobas', 'id_departamento' => 13],
            ['nombre' => 'Momil', 'id_departamento' => 13],
            ['nombre' => 'Montelíbano', 'id_departamento' => 13],
            ['nombre' => 'Monteria', 'id_departamento' => 13],
            ['nombre' => 'Moñitos', 'id_departamento' => 13],
            ['nombre' => 'Planeta Rica', 'id_departamento' => 13],
            ['nombre' => 'Pueblo Nuevo', 'id_departamento' => 13],
            ['nombre' => 'Puerto Escondido', 'id_departamento' => 13],
            ['nombre' => 'Puerto Libertador', 'id_departamento' => 13],
            ['nombre' => 'Purísima', 'id_departamento' => 13],
            ['nombre' => 'Sahagún', 'id_departamento' => 13],
            ['nombre' => 'San Andrés Sotavento', 'id_departamento' => 13],
            ['nombre' => 'San Antero', 'id_departamento' => 13],
            ['nombre' => 'San Bernardo del Viento', 'id_departamento' => 13],
            ['nombre' => 'San Carlos', 'id_departamento' => 13],
            ['nombre' => 'San José de Uré', 'id_departamento' => 13],
            ['nombre' => 'San Pelayo', 'id_departamento' => 13],
            ['nombre' => 'Tierralta', 'id_departamento' => 13],
            ['nombre' => 'Tuchín', 'id_departamento' => 13],
            ['nombre' => 'Valencia', 'id_departamento' => 13],
            ['nombre' => 'Agua de Dios', 'id_departamento' => 10],
            ['nombre' => 'Albán', 'id_departamento' => 10],
            ['nombre' => 'Anapoima', 'id_departamento' => 10],
            ['nombre' => 'Anolaima', 'id_departamento' => 10],
            ['nombre' => 'Apulo', 'id_departamento' => 10],
            ['nombre' => 'Arbeláez', 'id_departamento' => 10],
            ['nombre' => 'Beltrán', 'id_departamento' => 10],
            ['nombre' => 'Bituima', 'id_departamento' => 10],
            ['nombre' => 'Bogotá D.C.', 'id_departamento' => 10],
            ['nombre' => 'Bojacá', 'id_departamento' => 10],
            ['nombre' => 'Cabrera', 'id_departamento' => 10],
            ['nombre' => 'Cachipay', 'id_departamento' => 10],
            ['nombre' => 'Cajicá', 'id_departamento' => 10],
            ['nombre' => 'Caparrapí', 'id_departamento' => 10],
            ['nombre' => 'Carmen de Carupa', 'id_departamento' => 10],
            ['nombre' => 'Chaguaní', 'id_departamento' => 10],
            ['nombre' => 'Chipaque', 'id_departamento' => 10],
            ['nombre' => 'Choachí', 'id_departamento' => 10],
            ['nombre' => 'Chocontá', 'id_departamento' => 10],
            ['nombre' => 'Chía', 'id_departamento' => 10],
            ['nombre' => 'Cogua', 'id_departamento' => 10],
            ['nombre' => 'Cota', 'id_departamento' => 10],
            ['nombre' => 'Cucunubá', 'id_departamento' => 10],
            ['nombre' => 'Cáqueza', 'id_departamento' => 10],
            ['nombre' => 'El Colegio', 'id_departamento' => 10],
            ['nombre' => 'El Peñón', 'id_departamento' => 10],
            ['nombre' => 'El Rosal', 'id_departamento' => 10],
            ['nombre' => 'Facatativá', 'id_departamento' => 10],
            ['nombre' => 'Fosca', 'id_departamento' => 10],
            ['nombre' => 'Funza', 'id_departamento' => 10],
            ['nombre' => 'Fusagasugá', 'id_departamento' => 10],
            ['nombre' => 'Fómeque', 'id_departamento' => 10],
            ['nombre' => 'Fúquene', 'id_departamento' => 10],
            ['nombre' => 'Gachalá', 'id_departamento' => 10],
            ['nombre' => 'Gachancipá', 'id_departamento' => 10],
            ['nombre' => 'Gachetá', 'id_departamento' => 10],
            ['nombre' => 'Gama', 'id_departamento' => 10],
            ['nombre' => 'Girardot', 'id_departamento' => 10],
            ['nombre' => 'Granada', 'id_departamento' => 10],
            ['nombre' => 'Guachetá', 'id_departamento' => 10],
            ['nombre' => 'Guaduas', 'id_departamento' => 10],
            ['nombre' => 'Guasca', 'id_departamento' => 10],
            ['nombre' => 'Guataquí', 'id_departamento' => 10],
            ['nombre' => 'Guatavita', 'id_departamento' => 10],
            ['nombre' => 'Guayabal de Siquima', 'id_departamento' => 10],
            ['nombre' => 'Guayabetal', 'id_departamento' => 10],
            ['nombre' => 'Gutiérrez', 'id_departamento' => 10],
            ['nombre' => 'Jerusalén', 'id_departamento' => 10],
            ['nombre' => 'Junín', 'id_departamento' => 10],
            ['nombre' => 'La Calera', 'id_departamento' => 10],
            ['nombre' => 'La Mesa', 'id_departamento' => 10],
            ['nombre' => 'La Palma', 'id_departamento' => 10],
            ['nombre' => 'La Peña', 'id_departamento' => 10],
            ['nombre' => 'La Vega', 'id_departamento' => 10],
            ['nombre' => 'Lenguazaque', 'id_departamento' => 10],
            ['nombre' => 'Machetá', 'id_departamento' => 10],
            ['nombre' => 'Madrid', 'id_departamento' => 10],
            ['nombre' => 'Manta', 'id_departamento' => 10],
            ['nombre' => 'Medina', 'id_departamento' => 10],
            ['nombre' => 'Mosquera', 'id_departamento' => 10],
            ['nombre' => 'Nariño', 'id_departamento' => 10],
            ['nombre' => 'Nemocón', 'id_departamento' => 10],
            ['nombre' => 'Nilo', 'id_departamento' => 10],
            ['nombre' => 'Nimaima', 'id_departamento' => 10],
            ['nombre' => 'Nocaima', 'id_departamento' => 10],
            ['nombre' => 'Pacho', 'id_departamento' => 10],
            ['nombre' => 'Paime', 'id_departamento' => 10],
            ['nombre' => 'Pandi', 'id_departamento' => 10],
            ['nombre' => 'Paratebueno', 'id_departamento' => 10],
            ['nombre' => 'Pasca', 'id_departamento' => 10],
            ['nombre' => 'Puerto Salgar', 'id_departamento' => 10],
            ['nombre' => 'Pulí', 'id_departamento' => 10],
            ['nombre' => 'Quebradanegra', 'id_departamento' => 10],
            ['nombre' => 'Quetame', 'id_departamento' => 10],
            ['nombre' => 'Quipile', 'id_departamento' => 10],
            ['nombre' => 'Ricaurte', 'id_departamento' => 10],
            ['nombre' => 'San Antonio de Tequendama', 'id_departamento' => 10],
            ['nombre' => 'San Bernardo', 'id_departamento' => 10],
            ['nombre' => 'San Cayetano', 'id_departamento' => 10],
            ['nombre' => 'San Francisco', 'id_departamento' => 10],
            ['nombre' => 'San Juan de Río Seco', 'id_departamento' => 10],
            ['nombre' => 'Sasaima', 'id_departamento' => 10],
            ['nombre' => 'Sesquilé', 'id_departamento' => 10],
            ['nombre' => 'Sibaté', 'id_departamento' => 10],
            ['nombre' => 'Silvania', 'id_departamento' => 10],
            ['nombre' => 'Simijaca', 'id_departamento' => 10],
            ['nombre' => 'Soacha', 'id_departamento' => 10],
            ['nombre' => 'Sopó', 'id_departamento' => 10],
            ['nombre' => 'Subachoque', 'id_departamento' => 10],
            ['nombre' => 'Suesca', 'id_departamento' => 10],
            ['nombre' => 'Supatá', 'id_departamento' => 10],
            ['nombre' => 'Susa', 'id_departamento' => 10],
            ['nombre' => 'Sutatausa', 'id_departamento' => 10],
            ['nombre' => 'Tabio', 'id_departamento' => 10],
            ['nombre' => 'Tausa', 'id_departamento' => 10],
            ['nombre' => 'Tena', 'id_departamento' => 10],
            ['nombre' => 'Tenjo', 'id_departamento' => 10],
            ['nombre' => 'Tibacuy', 'id_departamento' => 10],
            ['nombre' => 'Tibirita', 'id_departamento' => 10],
            ['nombre' => 'Tocaima', 'id_departamento' => 10],
            ['nombre' => 'Tocancipá', 'id_departamento' => 10],
            ['nombre' => 'Topaipí', 'id_departamento' => 10],
            ['nombre' => 'Ubalá', 'id_departamento' => 10],
            ['nombre' => 'Ubaque', 'id_departamento' => 10],
            ['nombre' => 'Ubaté', 'id_departamento' => 10],
            ['nombre' => 'Une', 'id_departamento' => 10],
            ['nombre' => 'Venecia (Ospina Pérez)', 'id_departamento' => 10],
            ['nombre' => 'Vergara', 'id_departamento' => 10],
            ['nombre' => 'Viani', 'id_departamento' => 10],
            ['nombre' => 'Villagómez', 'id_departamento' => 10],
            ['nombre' => 'Villapinzón', 'id_departamento' => 10],
            ['nombre' => 'Villeta', 'id_departamento' => 10],
            ['nombre' => 'Viotá', 'id_departamento' => 10],
            ['nombre' => 'Yacopí', 'id_departamento' => 10],
            ['nombre' => 'Zipacón', 'id_departamento' => 10],
            ['nombre' => 'Zipaquirá', 'id_departamento' => 10],
            ['nombre' => 'Útica', 'id_departamento' => 10],
            ['nombre' => 'Inírida', 'id_departamento' => 16],
            ['nombre' => 'Calamar', 'id_departamento' => 18],
            ['nombre' => 'El Retorno', 'id_departamento' => 18],
            ['nombre' => 'Miraflores', 'id_departamento' => 18],
            ['nombre' => 'San José del Guaviare', 'id_departamento' => 18],
            ['nombre' => 'Acevedo', 'id_departamento' => 19],
            ['nombre' => 'Agrado', 'id_departamento' => 19],
            ['nombre' => 'Aipe', 'id_departamento' => 19],
            ['nombre' => 'Algeciras', 'id_departamento' => 19],
            ['nombre' => 'Altamira', 'id_departamento' => 19],
            ['nombre' => 'Baraya', 'id_departamento' => 19],
            ['nombre' => 'Campoalegre', 'id_departamento' => 19],
            ['nombre' => 'Colombia', 'id_departamento' => 19],
            ['nombre' => 'Elías', 'id_departamento' => 19],
            ['nombre' => 'Garzón', 'id_departamento' => 19],
            ['nombre' => 'Gigante', 'id_departamento' => 19],
            ['nombre' => 'Guadalupe', 'id_departamento' => 19],
            ['nombre' => 'Hobo', 'id_departamento' => 19],
            ['nombre' => 'Isnos', 'id_departamento' => 19],
            ['nombre' => 'La Argentina', 'id_departamento' => 19],
            ['nombre' => 'La Plata', 'id_departamento' => 19],
            ['nombre' => 'Neiva', 'id_departamento' => 19],
            ['nombre' => 'Nátaga', 'id_departamento' => 19],
            ['nombre' => 'Oporapa', 'id_departamento' => 19],
            ['nombre' => 'Paicol', 'id_departamento' => 19],
            ['nombre' => 'Palermo', 'id_departamento' => 19],
            ['nombre' => 'Palestina', 'id_departamento' => 19],
            ['nombre' => 'Pital', 'id_departamento' => 19],
            ['nombre' => 'Pitalito', 'id_departamento' => 19],
            ['nombre' => 'Rivera', 'id_departamento' => 19],
            ['nombre' => 'Saladoblanco', 'id_departamento' => 19],
            ['nombre' => 'San Agustín', 'id_departamento' => 19],
            ['nombre' => 'Santa María', 'id_departamento' => 19],
            ['nombre' => 'Suaza', 'id_departamento' => 19],
            ['nombre' => 'Tarqui', 'id_departamento' => 19],
            ['nombre' => 'Tello', 'id_departamento' => 19],
            ['nombre' => 'Teruel', 'id_departamento' => 19],
            ['nombre' => 'Tesalia', 'id_departamento' => 19],
            ['nombre' => 'Timaná', 'id_departamento' => 19],
            ['nombre' => 'Villavieja', 'id_departamento' => 19],
            ['nombre' => 'Yaguará', 'id_departamento' => 19],
            ['nombre' => 'Íquira', 'id_departamento' => 19],
            ['nombre' => 'Albania', 'id_departamento' => 17],
            ['nombre' => 'Barrancas', 'id_departamento' => 17],
            ['nombre' => 'Dibulla', 'id_departamento' => 17],
            ['nombre' => 'Distracción', 'id_departamento' => 17],
            ['nombre' => 'El Molino', 'id_departamento' => 17],
            ['nombre' => 'Fonseca', 'id_departamento' => 17],
            ['nombre' => 'Hatonuevo', 'id_departamento' => 17],
            ['nombre' => 'La Jagua del Pilar', 'id_departamento' => 17],
            ['nombre' => 'Maicao', 'id_departamento' => 17],
            ['nombre' => 'Manaure', 'id_departamento' => 17],
            ['nombre' => 'Riohacha', 'id_departamento' => 17],
            ['nombre' => 'San Juan del Cesar', 'id_departamento' => 17],
            ['nombre' => 'Uribia', 'id_departamento' => 17],
            ['nombre' => 'Urumita', 'id_departamento' => 17],
            ['nombre' => 'Villanueva', 'id_departamento' => 17],
            ['nombre' => 'Algarrobo', 'id_departamento' => 20],
            ['nombre' => 'Aracataca', 'id_departamento' => 20],
            ['nombre' => 'Ariguaní (El Difícil)', 'id_departamento' => 20],
            ['nombre' => 'Cerro San Antonio', 'id_departamento' => 20],
            ['nombre' => 'Chivolo', 'id_departamento' => 20],
            ['nombre' => 'Ciénaga', 'id_departamento' => 20],
            ['nombre' => 'Concordia', 'id_departamento' => 20],
            ['nombre' => 'El Banco', 'id_departamento' => 20],
            ['nombre' => 'El Piñon', 'id_departamento' => 20],
            ['nombre' => 'El Retén', 'id_departamento' => 20],
            ['nombre' => 'Fundación', 'id_departamento' => 20],
            ['nombre' => 'Guamal', 'id_departamento' => 20],
            ['nombre' => 'Nueva Granada', 'id_departamento' => 20],
            ['nombre' => 'Pedraza', 'id_departamento' => 20],
            ['nombre' => 'Pijiño', 'id_departamento' => 20],
            ['nombre' => 'Pivijay', 'id_departamento' => 20],
            ['nombre' => 'Plato', 'id_departamento' => 20],
            ['nombre' => 'Puebloviejo', 'id_departamento' => 20],
            ['nombre' => 'Remolino', 'id_departamento' => 20],
            ['nombre' => 'Sabanas de San Angel (SAN ANGEL)', 'id_departamento' => 20],
            ['nombre' => 'Salamina', 'id_departamento' => 20],
            ['nombre' => 'San Sebastián de Buenavista', 'id_departamento' => 20],
            ['nombre' => 'San Zenón', 'id_departamento' => 20],
            ['nombre' => 'Santa Ana', 'id_departamento' => 20],
            ['nombre' => 'Santa Bárbara de Pinto', 'id_departamento' => 20],
            ['nombre' => 'Santa Marta', 'id_departamento' => 20],
            ['nombre' => 'Sitionuevo', 'id_departamento' => 20],
            ['nombre' => 'Tenerife', 'id_departamento' => 20],
            ['nombre' => 'Zapayán (PUNTA DE PIEDRAS)', 'id_departamento' => 20],
            ['nombre' => 'Zona Bananera (PRADO - SEVILLA)', 'id_departamento' => 20],
            ['nombre' => 'Acacías', 'id_departamento' => 21],
            ['nombre' => 'Barranca de Upía', 'id_departamento' => 21],
            ['nombre' => 'Cabuyaro', 'id_departamento' => 21],
            ['nombre' => 'Castilla la Nueva', 'id_departamento' => 21],
            ['nombre' => 'Cubarral', 'id_departamento' => 21],
            ['nombre' => 'Cumaral', 'id_departamento' => 21],
            ['nombre' => 'El Calvario', 'id_departamento' => 21],
            ['nombre' => 'El Castillo', 'id_departamento' => 21],
            ['nombre' => 'El Dorado', 'id_departamento' => 21],
            ['nombre' => 'Fuente de Oro', 'id_departamento' => 21],
            ['nombre' => 'Granada', 'id_departamento' => 21],
            ['nombre' => 'Guamal', 'id_departamento' => 21],
            ['nombre' => 'La Macarena', 'id_departamento' => 21],
            ['nombre' => 'Lejanías', 'id_departamento' => 21],
            ['nombre' => 'Mapiripan', 'id_departamento' => 21],
            ['nombre' => 'Mesetas', 'id_departamento' => 21],
            ['nombre' => 'Puerto Concordia', 'id_departamento' => 21],
            ['nombre' => 'Puerto Gaitán', 'id_departamento' => 21],
            ['nombre' => 'Puerto Lleras', 'id_departamento' => 21],
            ['nombre' => 'Puerto López', 'id_departamento' => 21],
            ['nombre' => 'Puerto Rico', 'id_departamento' => 21],
            ['nombre' => 'Restrepo', 'id_departamento' => 21],
            ['nombre' => 'San Carlos de Guaroa', 'id_departamento' => 21],
            ['nombre' => 'San Juan de Arama', 'id_departamento' => 21],
            ['nombre' => 'San Juanito', 'id_departamento' => 21],
            ['nombre' => 'San Martín', 'id_departamento' => 21],
            ['nombre' => 'Uribe', 'id_departamento' => 21],
            ['nombre' => 'Villavicencio', 'id_departamento' => 21],
            ['nombre' => 'Vista Hermosa', 'id_departamento' => 21],
            ['nombre' => 'Albán (San José)', 'id_departamento' => 22],
            ['nombre' => 'Aldana', 'id_departamento' => 22],
            ['nombre' => 'Ancuya', 'id_departamento' => 22],
            ['nombre' => 'Arboleda (Berruecos)', 'id_departamento' => 22],
            ['nombre' => 'Barbacoas', 'id_departamento' => 22],
            ['nombre' => 'Belén', 'id_departamento' => 22],
            ['nombre' => 'Buesaco', 'id_departamento' => 22],
            ['nombre' => 'Chachaguí', 'id_departamento' => 22],
            ['nombre' => 'Colón (Génova)', 'id_departamento' => 22],
            ['nombre' => 'Consaca', 'id_departamento' => 22],
            ['nombre' => 'Contadero', 'id_departamento' => 22],
            ['nombre' => 'Cuaspud (Carlosama)', 'id_departamento' => 22],
            ['nombre' => 'Cumbal', 'id_departamento' => 22],
            ['nombre' => 'Cumbitara', 'id_departamento' => 22],
            ['nombre' => 'Córdoba', 'id_departamento' => 22],
            ['nombre' => 'El Charco', 'id_departamento' => 22],
            ['nombre' => 'El Peñol', 'id_departamento' => 22],
            ['nombre' => 'El Rosario', 'id_departamento' => 22],
            ['nombre' => 'El Tablón de Gómez', 'id_departamento' => 22],
            ['nombre' => 'El Tambo', 'id_departamento' => 22],
            ['nombre' => 'Francisco Pizarro', 'id_departamento' => 22],
            ['nombre' => 'Funes', 'id_departamento' => 22],
            ['nombre' => 'Guachavés', 'id_departamento' => 22],
            ['nombre' => 'Guachucal', 'id_departamento' => 22],
            ['nombre' => 'Guaitarilla', 'id_departamento' => 22],
            ['nombre' => 'Gualmatán', 'id_departamento' => 22],
            ['nombre' => 'Iles', 'id_departamento' => 22],
            ['nombre' => 'Imúes', 'id_departamento' => 22],
            ['nombre' => 'Ipiales', 'id_departamento' => 22],
            ['nombre' => 'La Cruz', 'id_departamento' => 22],
            ['nombre' => 'La Florida', 'id_departamento' => 22],
            ['nombre' => 'La Llanada', 'id_departamento' => 22],
            ['nombre' => 'La Tola', 'id_departamento' => 22],
            ['nombre' => 'La Unión', 'id_departamento' => 22],
            ['nombre' => 'Leiva', 'id_departamento' => 22],
            ['nombre' => 'Linares', 'id_departamento' => 22],
            ['nombre' => 'Magüi (Payán)', 'id_departamento' => 22],
            ['nombre' => 'Mallama (Piedrancha)', 'id_departamento' => 22],
            ['nombre' => 'Mosquera', 'id_departamento' => 22],
            ['nombre' => 'Nariño', 'id_departamento' => 22],
            ['nombre' => 'Olaya Herrera', 'id_departamento' => 22],
            ['nombre' => 'Ospina', 'id_departamento' => 22],
            ['nombre' => 'Policarpa', 'id_departamento' => 22],
            ['nombre' => 'Potosí', 'id_departamento' => 22],
            ['nombre' => 'Providencia', 'id_departamento' => 22],
            ['nombre' => 'Puerres', 'id_departamento' => 22],
            ['nombre' => 'Pupiales', 'id_departamento' => 22],
            ['nombre' => 'Ricaurte', 'id_departamento' => 22],
            ['nombre' => 'Roberto Payán (San José)', 'id_departamento' => 22],
            ['nombre' => 'Samaniego', 'id_departamento' => 22],
            ['nombre' => 'San Bernardo', 'id_departamento' => 22],
            ['nombre' => 'San Juan de Pasto', 'id_departamento' => 22],
            ['nombre' => 'San Lorenzo', 'id_departamento' => 22],
            ['nombre' => 'San Pablo', 'id_departamento' => 22],
            ['nombre' => 'San Pedro de Cartago', 'id_departamento' => 22],
            ['nombre' => 'Sandoná', 'id_departamento' => 22],
            ['nombre' => 'Santa Bárbara (Iscuandé)', 'id_departamento' => 22],
            ['nombre' => 'Sapuyes', 'id_departamento' => 22],
            ['nombre' => 'Sotomayor (Los Andes)', 'id_departamento' => 22],
            ['nombre' => 'Taminango', 'id_departamento' => 22],
            ['nombre' => 'Tangua', 'id_departamento' => 22],
            ['nombre' => 'Tumaco', 'id_departamento' => 22],
            ['nombre' => 'Túquerres', 'id_departamento' => 22],
            ['nombre' => 'Yacuanquer', 'id_departamento' => 22],
            ['nombre' => 'Arboledas', 'id_departamento' => 23],
            ['nombre' => 'Bochalema', 'id_departamento' => 23],
            ['nombre' => 'Bucarasica', 'id_departamento' => 23],
            ['nombre' => 'Chinácota', 'id_departamento' => 23],
            ['nombre' => 'Chitagá', 'id_departamento' => 23],
            ['nombre' => 'Convención', 'id_departamento' => 23],
            ['nombre' => 'Cucutilla', 'id_departamento' => 23],
            ['nombre' => 'Cáchira', 'id_departamento' => 23],
            ['nombre' => 'Cácota', 'id_departamento' => 23],
            ['nombre' => 'Cúcuta', 'id_departamento' => 23],
            ['nombre' => 'Durania', 'id_departamento' => 23],
            ['nombre' => 'El Carmen', 'id_departamento' => 23],
            ['nombre' => 'El Tarra', 'id_departamento' => 23],
            ['nombre' => 'El Zulia', 'id_departamento' => 23],
            ['nombre' => 'Gramalote', 'id_departamento' => 23],
            ['nombre' => 'Hacarí', 'id_departamento' => 23],
            ['nombre' => 'Herrán', 'id_departamento' => 23],
            ['nombre' => 'La Esperanza', 'id_departamento' => 23],
            ['nombre' => 'La Playa', 'id_departamento' => 23],
            ['nombre' => 'Labateca', 'id_departamento' => 23],
            ['nombre' => 'Los Patios', 'id_departamento' => 23],
            ['nombre' => 'Lourdes', 'id_departamento' => 23],
            ['nombre' => 'Mutiscua', 'id_departamento' => 23],
            ['nombre' => 'Ocaña', 'id_departamento' => 23],
            ['nombre' => 'Pamplona', 'id_departamento' => 23],
            ['nombre' => 'Pamplonita', 'id_departamento' => 23],
            ['nombre' => 'Puerto Santander', 'id_departamento' => 23],
            ['nombre' => 'Ragonvalia', 'id_departamento' => 23],
            ['nombre' => 'Salazar', 'id_departamento' => 23],
            ['nombre' => 'San Calixto', 'id_departamento' => 23],
            ['nombre' => 'San Cayetano', 'id_departamento' => 23],
            ['nombre' => 'Santiago', 'id_departamento' => 23],
            ['nombre' => 'Sardinata', 'id_departamento' => 23],
            ['nombre' => 'Silos', 'id_departamento' => 23],
            ['nombre' => 'Teorama', 'id_departamento' => 23],
            ['nombre' => 'Tibú', 'id_departamento' => 23],
            ['nombre' => 'Toledo', 'id_departamento' => 23],
            ['nombre' => 'Villa Caro', 'id_departamento' => 23],
            ['nombre' => 'Villa del Rosario', 'id_departamento' => 23],
            ['nombre' => 'Ábrego', 'id_departamento' => 23],
            ['nombre' => 'Colón', 'id_departamento' => 24],
            ['nombre' => 'Mocoa', 'id_departamento' => 24],
            ['nombre' => 'Orito', 'id_departamento' => 24],
            ['nombre' => 'Puerto Asís', 'id_departamento' => 24],
            ['nombre' => 'Puerto Caicedo', 'id_departamento' => 24],
            ['nombre' => 'Puerto Guzmán', 'id_departamento' => 24],
            ['nombre' => 'Puerto Leguízamo', 'id_departamento' => 24],
            ['nombre' => 'San Francisco', 'id_departamento' => 24],
            ['nombre' => 'San Miguel', 'id_departamento' => 24],
            ['nombre' => 'Santiago', 'id_departamento' => 24],
            ['nombre' => 'Sibundoy', 'id_departamento' => 24],
            ['nombre' => 'Valle del Guamuez', 'id_departamento' => 24],
            ['nombre' => 'Villagarzón', 'id_departamento' => 24],
            ['nombre' => 'Armenia', 'id_departamento' => 25],
            ['nombre' => 'Buenavista', 'id_departamento' => 25],
            ['nombre' => 'Calarcá', 'id_departamento' => 25],
            ['nombre' => 'Circasia', 'id_departamento' => 25],
            ['nombre' => 'Cordobá', 'id_departamento' => 25],
            ['nombre' => 'Filandia', 'id_departamento' => 25],
            ['nombre' => 'Génova', 'id_departamento' => 25],
            ['nombre' => 'La Tebaida', 'id_departamento' => 25],
            ['nombre' => 'Montenegro', 'id_departamento' => 25],
            ['nombre' => 'Pijao', 'id_departamento' => 25],
            ['nombre' => 'Quimbaya', 'id_departamento' => 25],
            ['nombre' => 'Salento', 'id_departamento' => 25],
            ['nombre' => 'Apía', 'id_departamento' => 26],
            ['nombre' => 'Balboa', 'id_departamento' => 26],
            ['nombre' => 'Belén de Umbría', 'id_departamento' => 26],
            ['nombre' => 'Dos Quebradas', 'id_departamento' => 26],
            ['nombre' => 'Guática', 'id_departamento' => 26],
            ['nombre' => 'La Celia', 'id_departamento' => 26],
            ['nombre' => 'La Virginia', 'id_departamento' => 26],
            ['nombre' => 'Marsella', 'id_departamento' => 26],
            ['nombre' => 'Mistrató', 'id_departamento' => 26],
            ['nombre' => 'Pereira', 'id_departamento' => 26],
            ['nombre' => 'Pueblo Rico', 'id_departamento' => 26],
            ['nombre' => 'Quinchía', 'id_departamento' => 26],
            ['nombre' => 'Santa Rosa de Cabal', 'id_departamento' => 26],
            ['nombre' => 'Santuario', 'id_departamento' => 26],
            ['nombre' => 'Providencia', 'id_departamento' => 3],
            ['nombre' => 'Aguada', 'id_departamento' => 27],
            ['nombre' => 'Albania', 'id_departamento' => 27],
            ['nombre' => 'Aratoca', 'id_departamento' => 27],
            ['nombre' => 'Barbosa', 'id_departamento' => 27],
            ['nombre' => 'Barichara', 'id_departamento' => 27],
            ['nombre' => 'Barrancabermeja', 'id_departamento' => 27],
            ['nombre' => 'Betulia', 'id_departamento' => 27],
            ['nombre' => 'Bolívar', 'id_departamento' => 27],
            ['nombre' => 'Bucaramanga', 'id_departamento' => 27],
            ['nombre' => 'Cabrera', 'id_departamento' => 27],
            ['nombre' => 'California', 'id_departamento' => 27],
            ['nombre' => 'Capitanejo', 'id_departamento' => 27],
            ['nombre' => 'Carcasí', 'id_departamento' => 27],
            ['nombre' => 'Cepita', 'id_departamento' => 27],
            ['nombre' => 'Cerrito', 'id_departamento' => 27],
            ['nombre' => 'Charalá', 'id_departamento' => 27],
            ['nombre' => 'Charta', 'id_departamento' => 27],
            ['nombre' => 'Chima', 'id_departamento' => 27],
            ['nombre' => 'Chipatá', 'id_departamento' => 27],
            ['nombre' => 'Cimitarra', 'id_departamento' => 27],
            ['nombre' => 'Concepción', 'id_departamento' => 27],
            ['nombre' => 'Confines', 'id_departamento' => 27],
            ['nombre' => 'Contratación', 'id_departamento' => 27],
            ['nombre' => 'Coromoro', 'id_departamento' => 27],
            ['nombre' => 'Curití', 'id_departamento' => 27],
            ['nombre' => 'El Carmen', 'id_departamento' => 27],
            ['nombre' => 'El Guacamayo', 'id_departamento' => 27],
            ['nombre' => 'El Peñon', 'id_departamento' => 27],
            ['nombre' => 'El Playón', 'id_departamento' => 27],
            ['nombre' => 'Encino', 'id_departamento' => 27],
            ['nombre' => 'Enciso', 'id_departamento' => 27],
            ['nombre' => 'Floridablanca', 'id_departamento' => 27],
            ['nombre' => 'Florián', 'id_departamento' => 27],
            ['nombre' => 'Galán', 'id_departamento' => 27],
            ['nombre' => 'Girón', 'id_departamento' => 27],
            ['nombre' => 'Guaca', 'id_departamento' => 27],
            ['nombre' => 'Guadalupe', 'id_departamento' => 27],
            ['nombre' => 'Guapota', 'id_departamento' => 27],
            ['nombre' => 'Guavatá', 'id_departamento' => 27],
            ['nombre' => 'Guepsa', 'id_departamento' => 27],
            ['nombre' => 'Gámbita', 'id_departamento' => 27],
            ['nombre' => 'Hato', 'id_departamento' => 27],
            ['nombre' => 'Jesús María', 'id_departamento' => 27],
            ['nombre' => 'Jordán', 'id_departamento' => 27],
            ['nombre' => 'La Belleza', 'id_departamento' => 27],
            ['nombre' => 'La Paz', 'id_departamento' => 27],
            ['nombre' => 'Landázuri', 'id_departamento' => 27],
            ['nombre' => 'Lebrija', 'id_departamento' => 27],
            ['nombre' => 'Los Santos', 'id_departamento' => 27],
            ['nombre' => 'Macaravita', 'id_departamento' => 27],
            ['nombre' => 'Matanza', 'id_departamento' => 27],
            ['nombre' => 'Mogotes', 'id_departamento' => 27],
            ['nombre' => 'Molagavita', 'id_departamento' => 27],
            ['nombre' => 'Málaga', 'id_departamento' => 27],
            ['nombre' => 'Ocamonte', 'id_departamento' => 27],
            ['nombre' => 'Oiba', 'id_departamento' => 27],
            ['nombre' => 'Onzaga', 'id_departamento' => 27],
            ['nombre' => 'Palmar', 'id_departamento' => 27],
            ['nombre' => 'Palmas del Socorro', 'id_departamento' => 27],
            ['nombre' => 'Pie de Cuesta', 'id_departamento' => 27],
            ['nombre' => 'Pinchote', 'id_departamento' => 27],
            ['nombre' => 'Puente Nacional', 'id_departamento' => 27],
            ['nombre' => 'Puerto Parra', 'id_departamento' => 27],
            ['nombre' => 'Puerto Wilches', 'id_departamento' => 27],
            ['nombre' => 'Páramo', 'id_departamento' => 27],
            ['nombre' => 'Rio Negro', 'id_departamento' => 27],
            ['nombre' => 'Sabana de Torres', 'id_departamento' => 27],
            ['nombre' => 'San Andrés', 'id_departamento' => 27],
            ['nombre' => 'San Benito', 'id_departamento' => 27],
            ['nombre' => 'San Gíl', 'id_departamento' => 27],
            ['nombre' => 'San Joaquín', 'id_departamento' => 27],
            ['nombre' => 'San José de Miranda', 'id_departamento' => 27],
            ['nombre' => 'San Miguel', 'id_departamento' => 27],
            ['nombre' => 'San Vicente del Chucurí', 'id_departamento' => 27],
            ['nombre' => 'Santa Bárbara', 'id_departamento' => 27],
            ['nombre' => 'Santa Helena del Opón', 'id_departamento' => 27],
            ['nombre' => 'Simacota', 'id_departamento' => 27],
            ['nombre' => 'Socorro', 'id_departamento' => 27],
            ['nombre' => 'Suaita', 'id_departamento' => 27],
            ['nombre' => 'Sucre', 'id_departamento' => 27],
            ['nombre' => 'Suratá', 'id_departamento' => 27],
            ['nombre' => 'Tona', 'id_departamento' => 27],
            ['nombre' => 'Valle de San José', 'id_departamento' => 27],
            ['nombre' => 'Vetas', 'id_departamento' => 27],
            ['nombre' => 'Villanueva', 'id_departamento' => 27],
            ['nombre' => 'Vélez', 'id_departamento' => 27],
            ['nombre' => 'Zapatoca', 'id_departamento' => 27],
            ['nombre' => 'Buenavista', 'id_departamento' => 28],
            ['nombre' => 'Caimito', 'id_departamento' => 28],
            ['nombre' => 'Chalán', 'id_departamento' => 28],
            ['nombre' => 'Colosó (Ricaurte)', 'id_departamento' => 28],
            ['nombre' => 'Corozal', 'id_departamento' => 28],
            ['nombre' => 'Coveñas', 'id_departamento' => 28],
            ['nombre' => 'El Roble', 'id_departamento' => 28],
            ['nombre' => 'Galeras (Nueva Granada)', 'id_departamento' => 28],
            ['nombre' => 'Guaranda', 'id_departamento' => 28],
            ['nombre' => 'La Unión', 'id_departamento' => 28],
            ['nombre' => 'Los Palmitos', 'id_departamento' => 28],
            ['nombre' => 'Majagual', 'id_departamento' => 28],
            ['nombre' => 'Morroa', 'id_departamento' => 28],
            ['nombre' => 'Ovejas', 'id_departamento' => 28],
            ['nombre' => 'Palmito', 'id_departamento' => 28],
            ['nombre' => 'Sampués', 'id_departamento' => 28],
            ['nombre' => 'San Benito Abad', 'id_departamento' => 28],
            ['nombre' => 'San Juan de Betulia', 'id_departamento' => 28],
            ['nombre' => 'San Marcos', 'id_departamento' => 28],
            ['nombre' => 'San Onofre', 'id_departamento' => 28],
            ['nombre' => 'San Pedro', 'id_departamento' => 28],
            ['nombre' => 'Sincelejo', 'id_departamento' => 28],
            ['nombre' => 'Sincé', 'id_departamento' => 28],
            ['nombre' => 'Sucre', 'id_departamento' => 28],
            ['nombre' => 'Tolú', 'id_departamento' => 28],
            ['nombre' => 'Tolú Viejo', 'id_departamento' => 28],
            ['nombre' => 'Alpujarra', 'id_departamento' => 29],
            ['nombre' => 'Alvarado', 'id_departamento' => 29],
            ['nombre' => 'Ambalema', 'id_departamento' => 29],
            ['nombre' => 'Anzoátegui', 'id_departamento' => 29],
            ['nombre' => 'Armero (Guayabal)', 'id_departamento' => 29],
            ['nombre' => 'Ataco', 'id_departamento' => 29],
            ['nombre' => 'Cajamarca', 'id_departamento' => 29],
            ['nombre' => 'Carmen de Apicalá', 'id_departamento' => 29],
            ['nombre' => 'Casabianca', 'id_departamento' => 29],
            ['nombre' => 'Chaparral', 'id_departamento' => 29],
            ['nombre' => 'Coello', 'id_departamento' => 29],
            ['nombre' => 'Coyaima', 'id_departamento' => 29],
            ['nombre' => 'Cunday', 'id_departamento' => 29],
            ['nombre' => 'Dolores', 'id_departamento' => 29],
            ['nombre' => 'Espinal', 'id_departamento' => 29],
            ['nombre' => 'Falan', 'id_departamento' => 29],
            ['nombre' => 'Flandes', 'id_departamento' => 29],
            ['nombre' => 'Fresno', 'id_departamento' => 29],
            ['nombre' => 'Guamo', 'id_departamento' => 29],
            ['nombre' => 'Herveo', 'id_departamento' => 29],
            ['nombre' => 'Honda', 'id_departamento' => 29],
            ['nombre' => 'Ibagué', 'id_departamento' => 29],
            ['nombre' => 'Icononzo', 'id_departamento' => 29],
            ['nombre' => 'Lérida', 'id_departamento' => 29],
            ['nombre' => 'Líbano', 'id_departamento' => 29],
            ['nombre' => 'Mariquita', 'id_departamento' => 29],
            ['nombre' => 'Melgar', 'id_departamento' => 29],
            ['nombre' => 'Murillo', 'id_departamento' => 29],
            ['nombre' => 'Natagaima', 'id_departamento' => 29],
            ['nombre' => 'Ortega', 'id_departamento' => 29],
            ['nombre' => 'Palocabildo', 'id_departamento' => 29],
            ['nombre' => 'Piedras', 'id_departamento' => 29],
            ['nombre' => 'Planadas', 'id_departamento' => 29],
            ['nombre' => 'Prado', 'id_departamento' => 29],
            ['nombre' => 'Purificación', 'id_departamento' => 29],
            ['nombre' => 'Rioblanco', 'id_departamento' => 29],
            ['nombre' => 'Roncesvalles', 'id_departamento' => 29],
            ['nombre' => 'Rovira', 'id_departamento' => 29],
            ['nombre' => 'Saldaña', 'id_departamento' => 29],
            ['nombre' => 'San Antonio', 'id_departamento' => 29],
            ['nombre' => 'San Luis', 'id_departamento' => 29],
            ['nombre' => 'Santa Isabel', 'id_departamento' => 29],
            ['nombre' => 'Suárez', 'id_departamento' => 29],
            ['nombre' => 'Valle de San Juan', 'id_departamento' => 29],
            ['nombre' => 'Venadillo', 'id_departamento' => 29],
            ['nombre' => 'Villahermosa', 'id_departamento' => 29],
            ['nombre' => 'Villarrica', 'id_departamento' => 29],
            ['nombre' => 'Alcalá', 'id_departamento' => 31],
            ['nombre' => 'Andalucía', 'id_departamento' => 31],
            ['nombre' => 'Ansermanuevo', 'id_departamento' => 31],
            ['nombre' => 'Argelia', 'id_departamento' => 31],
            ['nombre' => 'Bolívar', 'id_departamento' => 31],
            ['nombre' => 'Buenaventura', 'id_departamento' => 31],
            ['nombre' => 'Buga', 'id_departamento' => 31],
            ['nombre' => 'Bugalagrande', 'id_departamento' => 31],
            ['nombre' => 'Caicedonia', 'id_departamento' => 31],
            ['nombre' => 'Calima (Darién)', 'id_departamento' => 31],
            ['nombre' => 'Calí', 'id_departamento' => 31],
            ['nombre' => 'Candelaria', 'id_departamento' => 31],
            ['nombre' => 'Cartago', 'id_departamento' => 31],
            ['nombre' => 'Dagua', 'id_departamento' => 31],
            ['nombre' => 'El Cairo', 'id_departamento' => 31],
            ['nombre' => 'El Cerrito', 'id_departamento' => 31],
            ['nombre' => 'El Dovio', 'id_departamento' => 31],
            ['nombre' => 'El Águila', 'id_departamento' => 31],
            ['nombre' => 'Florida', 'id_departamento' => 31],
            ['nombre' => 'Ginebra', 'id_departamento' => 31],
            ['nombre' => 'Guacarí', 'id_departamento' => 31],
            ['nombre' => 'Jamundí', 'id_departamento' => 31],
            ['nombre' => 'La Cumbre', 'id_departamento' => 31],
            ['nombre' => 'La Unión', 'id_departamento' => 31],
            ['nombre' => 'La Victoria', 'id_departamento' => 31],
            ['nombre' => 'Obando', 'id_departamento' => 31],
            ['nombre' => 'Palmira', 'id_departamento' => 31],
            ['nombre' => 'Pradera', 'id_departamento' => 31],
            ['nombre' => 'Restrepo', 'id_departamento' => 31],
            ['nombre' => 'Riofrío', 'id_departamento' => 31],
            ['nombre' => 'Roldanillo', 'id_departamento' => 31],
            ['nombre' => 'San Pedro', 'id_departamento' => 31],
            ['nombre' => 'Sevilla', 'id_departamento' => 31],
            ['nombre' => 'Toro', 'id_departamento' => 31],
            ['nombre' => 'Trujillo', 'id_departamento' => 31],
            ['nombre' => 'Tulúa', 'id_departamento' => 31],
            ['nombre' => 'Ulloa', 'id_departamento' => 31],
            ['nombre' => 'Versalles', 'id_departamento' => 31],
            ['nombre' => 'Vijes', 'id_departamento' => 31],
            ['nombre' => 'Yotoco', 'id_departamento' => 31],
            ['nombre' => 'Yumbo', 'id_departamento' => 31],
            ['nombre' => 'Zarzal', 'id_departamento' => 31],
            ['nombre' => 'Carurú', 'id_departamento' => 30],
            ['nombre' => 'Mitú', 'id_departamento' => 30],
            ['nombre' => 'Taraira', 'id_departamento' => 30],
            ['nombre' => 'Cumaribo', 'id_departamento' => 32],
            ['nombre' => 'La Primavera', 'id_departamento' => 32],
            ['nombre' => 'Puerto Carreño', 'id_departamento' => 32],
            ['nombre' => 'Santa Rosalía', 'id_departamento' => 32],
        ];

        foreach ($ciudades as $ciudad) {
            DB::table('ciudad')->insert($ciudad);
        }
    }
}
